(() => {
const cfg=window.DONPONLINE_CONFIG||{}, client=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey); let episodes=[],products=[],unlocks=[],progress=[],user=null,balance=0,selected=null;
const $=s=>document.querySelector(s), fmt=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`, owned=e=>e.is_free||unlocks.some(u=>u.episode_id===e.id||['complete_series','premium_bundle'].includes(u.unlock_type));
const previousEpisode=e=>episodes.find(x=>x.episode_number===e.episode_number-1),canUnlock=e=>e.episode_number===1||owned(previousEpisode(e));
const bonus=['Behind the Scenes','Deleted Scenes','Director Commentary','Soundtrack','Character Profiles','Exclusive Digital Badge','Secret Game Character'];
function toast(t){const el=$('#cv-toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function render(){const grid=$('#episode-grid');grid.innerHTML=episodes.map(e=>{const p=progress.find(x=>x.episode_id===e.id),o=owned(e),available=o||canUnlock(e),prior=previousEpisode(e),pct=p?Math.min(100,p.progress_seconds/e.duration_seconds*100):0;return `<article class="episode-card ${o?'owned':available?'locked':'sequence-locked'}"><div class="episode-art" style="${e.thumbnail_url?`background-image:url('${e.thumbnail_url}')`:''}"><span>0${e.episode_number}</span><b>${o?'▶':available?'LOCKED':'ORDER LOCKED'}</b></div><div class="episode-copy"><div><small>${p?.completed?'✓ COMPLETED':p?.progress_seconds?'CONTINUE WATCHING':!available?`EPISODE ${prior.episode_number} REQUIRED`:e.is_free?'FREE EPISODE':`${e.token_price} MOTION COINS`}</small><time>${fmt(e.duration_seconds)}</time></div><h3>${e.title}</h3><p>${e.description}</p>${pct?`<div class="progress"><i style="width:${pct}%"></i></div>`:''}<button data-episode="${e.id}" ${available?'':'disabled'}>${o?'Watch Episode':available?`Unlock for ${e.token_price} Motion Coins`:`Unlock Episode ${prior.episode_number} First`}</button></div></article>`}).join('');
grid.querySelectorAll('[data-episode]').forEach(b=>b.onclick=()=>{const e=episodes.find(x=>x.id===b.dataset.episode);if(owned(e)) location.href=`watch/?episode=${encodeURIComponent(e.slug)}`;else if(canUnlock(e))openPurchase(products.find(p=>p.episode_id===e.id))});
const latest=[...progress].filter(p=>p.progress_seconds&&!p.completed).sort((a,b)=>new Date(b.last_watched_at)-new Date(a.last_watched_at))[0];if(latest){const e=episodes.find(x=>x.id===latest.episode_id);$('#continue-section').hidden=false;$('#continue-card').innerHTML=`<a class="continue" href="watch/?episode=${e.slug}"><span>▶</span><div><small>EPISODE ${e.episode_number}</small><h3>${e.title}</h3><p>Resume at ${fmt(latest.progress_seconds)}</p></div></a>`}
}
function openPurchase(p){if(!user){toast('New here? Create a free member account—or sign in—to unlock and watch.');setTimeout(()=>location.href='../members.html?return=crunkville#auth-section',1600);return}if(!p)return;const episode=episodes.find(e=>e.id===p.episode_id);if(episode&&!canUnlock(episode)){toast(`Unlock Episode ${episode.episode_number-1} first.`);return}selected=p;$('#purchase-title').textContent=p.product_type==='complete_series'?'Unlock Welcome to Crunkville Movie':p.title;$('#purchase-copy').textContent=p.product_type==='complete_series'?'Get permanent access to the complete movie, presented across all four episodes, for 300 Motion Coins.':p.description;$('#current-balance').textContent=`${balance} Motion Coins`;$('#purchase-price').textContent=`${p.token_price} Motion Coins`;$('#after-balance').textContent=`${Math.max(0,balance-p.token_price)} Motion Coins`;const err=$('#purchase-error');err.textContent=balance<p.token_price?`You need ${p.token_price-balance} more Motion Coins.`:'';$('#confirm-purchase').textContent=balance<p.token_price?'Open Coin Store':p.product_type==='complete_series'?'Unlock Movie':'Confirm Unlock';$('#purchase-dialog').showModal()}
async function buy(){if(balance<selected.token_price){location.href='../members.html#buy-coins';return}const b=$('#confirm-purchase');b.disabled=true;b.textContent='Unlocking…';const {data,error}=await client.rpc('purchase_crunkville',{p_product_id:selected.id});b.disabled=false;if(error){$('#purchase-error').textContent=error.message;return}balance=data.balance;$('#purchase-dialog').close();toast(data.status==='already_owned'?'Already in your library.':'Crunkville unlocked.');await loadMember();render()}
async function loadMember(){const {data:{user:u}}=await client.auth.getUser();user=u;if(!u)return;$('#guest-access').hidden=true;const [w,un,pr]=await Promise.all([client.from('wallets').select('balance').eq('user_id',u.id).single(),client.from('crunkville_user_unlocks').select('episode_id,unlock_type,product_id').eq('user_id',u.id),client.from('crunkville_watch_progress').select('*').eq('user_id',u.id)]);balance=w.data?.balance||0;unlocks=un.data||[];progress=pr.data||[];$('#wallet-link').textContent=`${balance} MOTION COINS`;$('#account-balance').textContent=`YOUR BALANCE: ${balance} MOTION COINS`}
function bindTrailers(){document.querySelectorAll('.trailer-choice').forEach(button=>button.onclick=()=>{const player=$('#trailer-player'),source=$('#trailer-source');document.querySelectorAll('.trailer-choice').forEach(x=>x.classList.toggle('active',x===button));source.src=button.dataset.trailer;source.type=button.dataset.type;$('#trailer-number').textContent=button.dataset.number;player.load();player.play().catch(()=>{});player.scrollIntoView({behavior:'smooth',block:'center'})})}
async function init(){const trailerStyles=document.createElement('link');trailerStyles.rel='stylesheet';trailerStyles.href='trailers.css';document.head.append(trailerStyles);const trailerSection=document.createElement('section');trailerSection.id='trailers';trailerSection.className='cv-section trailer-section';trailerSection.innerHTML=`<div class="cv-heading"><div><p>ENTER CRUNKVILLE</p><h2>WATCH THE<br>TRAILERS.</h2></div><span>TURN IT UP · FULLSCREEN READY</span></div><div class="trailer-cinema"><div class="trailer-screen"><video id="trailer-player" controls playsinline preload="metadata"><source id="trailer-source" src="../assets/videos/crunkville/welcome-to-crunkville-trailer-1.mp4" type="video/mp4"></video><div class="trailer-badge">OFFICIAL TRAILER <b id="trailer-number">01</b></div></div><div class="trailer-selector"><button class="trailer-choice active" data-trailer="../assets/videos/crunkville/welcome-to-crunkville-trailer-1.mp4" data-type="video/mp4" data-number="01"><span>01</span><div><small>WELCOME TO CRUNKVILLE</small><strong>OFFICIAL TRAILER 1</strong></div><b>PLAY ▶</b></button><button class="trailer-choice" data-trailer="../assets/videos/crunkville/welcome-to-crunkville-trailer-2.mov" data-type="video/quicktime" data-number="02"><span>02</span><div><small>WELCOME TO CRUNKVILLE</small><strong>OFFICIAL TRAILER 2</strong></div><b>PLAY ▶</b></button></div></div>`;document.querySelector('main').insertBefore(trailerSection,$('#continue-section'));bindTrailers();const [ep,prod]=await Promise.all([client.from('crunkville_episodes').select('*').eq('is_published',true).order('episode_number'),client.from('crunkville_products').select('*').eq('is_active',true)]);episodes=ep.data||[];products=prod.data||[];await loadMember();render();$('#bonus-grid').innerHTML=bonus.map((x,i)=>`<article><span>0${i+1}</span><h3>${x}</h3><p>Premium access · Coming Soon</p></article>`).join('');document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>openPurchase(products.find(p=>p.product_type===b.dataset.buy)));document.querySelector('[data-watch-full]').onclick=()=>{if(unlocks.some(u=>['complete_series','premium_bundle'].includes(u.unlock_type)))location.href='watch/?movie=full';else openPurchase(products.find(p=>p.product_type==='complete_series'))};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#purchase-dialog').close());$('#confirm-purchase').onclick=buy}
document.addEventListener('click',event=>{const button=event.target.closest?.('.trailer-choice[data-number="02"]');if(!button)return;setTimeout(()=>{const player=$('#trailer-player'),source=$('#trailer-source');source.src='../assets/videos/crunkville/welcome-to-crunkville-trailer-2-small.mp4';source.type='video/mp4';player.load();player.play().catch(()=>{})},0)});
init().catch(()=>{$('#episode-grid').innerHTML='<p class="cv-loading">The Crunkville catalog could not load. Please try again.</p>'});
})();
