create table if not exists public.crunkville_views (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  view_type text not null check (view_type in ('full_movie', 'episode')),
  episode_id uuid references public.crunkville_episodes(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  constraint crunkville_view_shape check (
    (view_type = 'full_movie' and episode_id is null)
    or (view_type = 'episode' and episode_id is not null)
  )
);

create index if not exists crunkville_views_viewed_at_idx on public.crunkville_views (viewed_at desc);
create index if not exists crunkville_views_episode_idx on public.crunkville_views (episode_id, viewed_at desc);
alter table public.crunkville_views enable row level security;

drop policy if exists "Owners can read Crunkville views" on public.crunkville_views;
create policy "Owners can read Crunkville views" on public.crunkville_views
for select to authenticated using (
  lower(coalesce(auth.jwt()->>'email', '')) in ('donp@donponline.com', 'donpbeats@gmail.com')
);

create or replace function public.record_crunkville_view(p_view_type text, p_episode_id uuid default null)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user uuid := auth.uid(); v_authorized boolean := false;
begin
  if v_user is null then raise exception 'Sign in required'; end if;
  if p_view_type not in ('full_movie', 'episode') then raise exception 'Invalid view type'; end if;
  if p_view_type = 'full_movie' then
    if p_episode_id is not null then raise exception 'Full movie cannot include an episode'; end if;
    select exists(select 1 from public.crunkville_user_unlocks where user_id=v_user and unlock_type in ('complete_series','premium_bundle')) into v_authorized;
  else
    if p_episode_id is null then raise exception 'Episode required'; end if;
    select exists(select 1 from public.crunkville_episodes e where e.id=p_episode_id and e.is_published and (e.is_free or exists(select 1 from public.crunkville_user_unlocks u where u.user_id=v_user and (u.episode_id=e.id or u.unlock_type in ('complete_series','premium_bundle'))))) into v_authorized;
  end if;
  if not v_authorized then raise exception 'Playback access required'; end if;
  insert into public.crunkville_views(user_id,view_type,episode_id) values(v_user,p_view_type,p_episode_id);
end $$;

revoke all on function public.record_crunkville_view(text,uuid) from public, anon;
grant execute on function public.record_crunkville_view(text,uuid) to authenticated;
revoke all on public.crunkville_views from anon, authenticated;
grant select on public.crunkville_views to authenticated;
